# -*- mode: ruby -*-
# vim: set ft=ruby :

linux_nodes = {
  "nfss" => { :ip => "192.168.60.10", :cpus => "1", :mem => "512" },
  "nfsc" => { :ip => "192.168.60.11", :cpus => "1", :mem => "512" }
}

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.box_version = "2004.01"
    linux_nodes.each_with_index do |(hostname, cfg), index|
        config.vm.define hostname do |node|
            # Set hostname for host
            node.vm.hostname = hostname
            node.vm.provider "virtualbox" do |v|
                v.memory = cfg[:mem]
                v.cpus = cfg[:cpus]
                # Set name for vm in Virtual Box
                v.name = hostname
            end
            # configure VMs network
            node.vm.network :"private_network",
            virtualbox__intnet: "net1",
            ip: cfg[:ip],
            :virtualbox__dhcp_enabled => false,
            :virtualbox__forward_mode => "nat",
            :virtualbox__netmask => "255.255.255.0",
            :virtualbox__gateway => "192.168.60.1"

            if node.vm.hostname == 'nfss'
                node.vm.provision "shell", path: "nfss_script.sh"
            else
                node.vm.provision "shell", path: "nfsc_script.sh"
            end
        end 
    end
end