---
- name: Creates ssh keys directory
  ansible.builtin.file:
    path: /home/borg/.ssh/
    state: directory
    owner: borg
    group: borg
    mode: 0700
  delegate_to: backup

- name: Creates ssh keys directory
  ansible.builtin.file:
    path: /root/.ssh/
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Generate an OpenSSH keypair with the default values (2048 bits, rsa)
  community.crypto.openssh_keypair:
    path: /root/.ssh/id_rsa
    size: 2048
  register: openssh_keypair_vars

- name: Put public key for borg user
  ansible.builtin.lineinfile:
    path: /home/borg/.ssh/authorized_keys
    line: "{{ openssh_keypair_vars.public_key }} borg"
    create: true
    owner: borg
    group: borg
    mode: 0600
  delegate_to: backup

- name: Get known_hosts fingerprint from backup
  ansible.builtin.shell:
    cat /etc/ssh/ssh_host_ecdsa_key.pub | awk '{ print $1 " " $2 }'
  register: host_key
  delegate_to: backup

- name: Add host to known_hosts
  ansible.builtin.lineinfile:
    line: "{{ item }} {{ host_key.stdout }}"
    path: /root/.ssh/known_hosts
    create: true
    owner: root
    group: root
    mode: 0600
  with_items: "{{ groups['backup_servers'] | map('extract', hostvars, ['ansible_host']) }}"
