# -*- mode: ruby -*-
# vim: set ft=ruby :
disk_controller = 'IDE' # MacOS. This setting is OS dependent. Details ttps://github.com/hashicorp/vagrant/issues/8105

MACHINES = {
    :zfs => {
        :box_name => "centos/7",
        # :box_version => "2004.01",
        :disks => {
            :sata1 => {
                :dfile => './sata1.vdi',
                :size => 512, # Megabytes
                :port => 1
            },
            :sata2 => {
                :dfile => './sata2.vdi',
                :size => 512,
                :port => 2
            },
            :sata3 => {
                :dfile => './sata3.vdi',
                :size => 512,
                :port => 3
            },
            :sata4 => {
                :dfile => './sata4.vdi',
                :size => 512,
                :port => 4
            },
            :sata5 => {
                :dfile => './sata5.vdi',
                :size => 512,
                :port => 5
            },
            :sata6 => {
                :dfile => './sata6.vdi',
                :size => 512,
                :port => 6
            },
            :sata7 => {
                :dfile => './sata7.vdi',
                :size => 512,
                :port => 7
            },
            :sata8 => {
                :dfile => './sata8.vdi',
                :size => 512,
                :port => 8
            },
        }
},
}
Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.box_version = boxconfig[:box_version]
            box.vm.host_name = "zfs"
            box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", "1024"]
                needsController = false
                boxconfig[:disks].each do |dname, dconf|
                    unless File.exist?(dconf[:dfile])
                        vb.customize ['createhd', '--filename', dconf[:dfile],
                        '--variant', 'Fixed', '--size', dconf[:size]]
                        needsController = true
                    end
                end
                    if needsController == true
                        vb.customize ["storagectl", :id, "--name", "SATA",
                        "--add", "sata" ]
                        boxconfig[:disks].each do |dname, dconf|
                            vb.customize ['storageattach', :id, '--storagectl',
                            'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd',
                            '--medium', dconf[:dfile]]
                        end
                    end
            end
            box.vm.provision "shell", inline: <<-SHELL
            #install zfs repo
            yum install -y http://download.zfsonlinux.org/epel/zfs-release.el7_8.noarch.rpm
            #import gpg key
            rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-zfsonlinux
            #install DKMS style packages for correct work ZFS
            yum install -y epel-release kernel-devel zfs
            #change ZFS repo
            yum-config-manager --disable zfs
            yum-config-manager --enable zfs-kmod
            yum install -y zfs
            #Add kernel module zfs
            modprobe zfs
            #install wget
            yum install -y wget
            # enable bash completion
            cd /usr/share/bash-completion/completions/
            curl -O https://raw.githubusercontent.com/openzfs/zfs/zfs-0.8-release/contrib/bash_completion.d/zfs
            chmod +x zfs
            SHELL
        end
    end
end