galaxy_info:
  role_name: postgres_replication
  author:
    - me
  description: Configure replication for PostgreSQL cluster
  company: X
  license: MIT / BSD
  min_ansible_version: 2.7
  platforms:
    - name: centos/stream8

  galaxy_tags: []
dependencies: []
