scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['
                192.168.2.4:9100',
                192.168.2.6:9100',
                172.16.1.2:9100',
                172.16.1.4:9100',
                172.16.1.1:9100',
                10.10.255.1:9100',
                192.168.2.11:9100',
                192.168.2.12:9100',
                192.168.2.13:9100'
                ]

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://172.16.1.2
        - http://172.16.1.4
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
