postgre_nodes:
  hosts:
    node1:
        ansible_host: 192.168.57.11
        ansible_private_key_file: .vagrant/machines/node1/virtualbox/private_key
        node_role: master
    node2:
        ansible_host: 192.168.57.12
        ansible_private_key_file: .vagrant/machines/node2/virtualbox/private_key
        node_role: slave

backup_servers:
  hosts:
    barman:
        ansible_host: 192.168.57.13
        ansible_private_key_file: .vagrant/machines/barman/virtualbox/private_key
