---
- name: Create and resize ext4 filesystem
  community.general.filesystem:
    fstype: ext4
    dev: "{{ item }}"
    resizefs: true
  with_items:
    - /dev/bd-vg/bd-lv

- name: Create and resize ext4 filesystem
  community.general.filesystem:
    fstype: ext4
    dev: "{{ item }}"
    resizefs: true
  with_items:
    - /dev/drbd0
  when: ansible_hostname == 'back-node1'

- name: Create a directory for mount
  ansible.builtin.file:
    path: /var/lib/pgsql/14/data
    state: directory

- name: Create a directory for mount
  ansible.builtin.file:
    path: /srv/share
    state: directory

- name: Mount partitions
  ansible.posix.mount:
    path: "{{ item.mount_point }}"
    src: "{{ item.name }}"
    fstype: ext4
    opts: rw,user
    state: mounted
  with_items:
    - { name: '/dev/bd-vg/bd-lv', mount_point: '/var/lib/pgsql/14/data' }
    - { name: '/dev/drbd0', mount_point: '/srv/share' }

- name: Set directory permissions for postgres
  ansible.builtin.file:
    path: /var/lib/pgsql/14/data
    state: directory
    recurse: true
    mode: '0700'
    owner: '26'
    group: '26'

- name: Clearing postgres data directory
  ansible.builtin.file:
    path: '/var/lib/pgsql/14/data/lost+found'
    state: absent

- name: Set directory permissions for nfs
  ansible.builtin.file:
    path: /srv/share
    state: directory
    recurse: true
    mode: '0777'
