routes_eth1: |
  192.168.255.4/30 via 192.168.255.2
  192.168.255.8/30 via 192.168.255.2
  192.168.255.12/30 via 192.168.255.2
  192.168.0.0/22 via 192.168.255.2

iptables_rules: |
  *filter
  :INPUT DROP [0:0]
  :FORWARD ACCEPT [0:0]
  :OUTPUT ACCEPT [0:0]
  :TRAFFIC - [0:0]
  :SSH-INPUT - [0:0]
  :SSH-INPUTTWO - [0:0]
  # INPUT definition
  -A INPUT -j TRAFFIC
  -A TRAFFIC -i lo -j ACCEPT
  -A TRAFFIC -p icmp --icmp-type any -j ACCEPT
  -A TRAFFIC -m state --state ESTABLISHED,RELATED -j ACCEPT
  # TRAFFIC chain for Port Knocking. The correct port sequence in this example is  8881 -> 7777 -> 9991
  # any other sequence will drop the traffic
  -A TRAFFIC -m state --state NEW -m tcp -p tcp -s 192.168.255.2 --dport 22 -m recent --rcheck --seconds 30 --name SSH2 -j ACCEPT
  -A TRAFFIC -m state --state NEW -m tcp -p tcp -m recent --name SSH2 --remove -j DROP
  -A TRAFFIC -m state --state NEW -m tcp -p tcp --dport 9991 -m recent --rcheck --name SSH1 -j SSH-INPUTTWO
  -A TRAFFIC -m state --state NEW -m tcp -p tcp -m recent --name SSH1 --remove -j DROP
  -A TRAFFIC -m state --state NEW -m tcp -p tcp --dport 7777 -m recent --rcheck --name SSH0 -j SSH-INPUT
  -A TRAFFIC -m state --state NEW -m tcp -p tcp -m recent --name SSH0 --remove -j DROP
  -A TRAFFIC -m state --state NEW -m tcp -p tcp --dport 8881 -m recent --name SSH0 --set -j DROP
  -A SSH-INPUT -m recent --name SSH1 --set -j DROP
  -A SSH-INPUTTWO -m recent --name SSH2 --set -j DROP
  -A TRAFFIC -j DROP
  COMMIT
  *nat
  :PREROUTING ACCEPT [0:0]
  :INPUT ACCEPT [0:0]
  :OUTPUT ACCEPT [0:0]
  :POSTROUTING ACCEPT [0:0]
  -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
  COMMIT

ansible_private_key_file: .vagrant/machines/inetRouter/virtualbox/private_key
