# -*- mode: ruby -*-
# vim: set ft=ruby :

Vagrant.configure("2") do |config|
  # Указываем ОС, версию, количество ядер и ОЗУ
  config.vm.box = "centos/8"
  # config.vm.box_version = "20210210.0"

  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.cpus = 1
  end

  # Указываем имена хостов и их IP-адреса
  boxes = [
    { :name => "ipa.otus.lan",
      :ip => "192.168.57.10",
    },
    { :name => "client1.otus.lan",
      :ip => "192.168.57.11",
    },
    { :name => "client2.otus.lan",
      :ip => "192.168.57.12",
    }
  ]
  # Цикл запуска виртуальных машин
  boxes.each_with_index do |(opts), index|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network "private_network", ip: opts[:ip]
    
      if index == boxes.size - 1
        config.vm.provision 'ansible' do |ansible|
          # ansible.verbose = "vvvvv"
          ansible.galaxy_roles_path = "ansible/roles"
          ansible.inventory_path = "ansible/inventory.yml"
          ansible.playbook = 'ansible/provision.yml'
          ansible.host_key_checking = "false"
          ansible.become = "true"
          ansible.limit = "all"
        end
      end
    end
  end
end
