dhcp_network:   "10.0.0.0"
dhcp_mask:      "255.255.255.0"
dhcp_range_min: "10.0.0.100"
dhcp_range_max: "10.0.0.120"
pxe_server:     "10.0.0.20"

ansible_port: 22
ansible_user: vagrant
# ansible_python_interpreter: /usr/bin/python3
