routers:
  hosts:
    inetRouter:
        ansible_host: 192.168.56.10
        ansible_ssh_private_key_file: .vagrant/machines/inetRouter/virtualbox/private_key
        bond_ip: 192.168.255.1
    centralRouter:
        ansible_host: 192.168.56.11
        ansible_ssh_private_key_file: .vagrant/machines/centralRouter/virtualbox/private_key
        bond_ip: 192.168.255.2
    office1Router:
        ansible_host: 192.168.56.20
        ansible_ssh_private_key_file: .vagrant/machines/office1Router/virtualbox/private_key 

servers:
  hosts:
    testServer1:
        ansible_host: 192.168.56.22
        ansible_ssh_private_key_file: .vagrant/machines/testServer1/virtualbox/private_key
        vlan_id: 1
        vlan_ip: 10.10.10.1
    testServer2:
        ansible_host: 192.168.56.32
        ansible_private_key_file: .vagrant/machines/testServer2/virtualbox/private_key
        vlan_id: 2
        vlan_ip: 10.10.10.1

clients:
  hosts:
    testClient1:
        ansible_host: 192.168.56.21
        ansible_ssh_private_key_file: .vagrant/machines/testClient1/virtualbox/private_key
        vlan_id: 1
        vlan_ip: 10.10.10.254
    testClient2:
        ansible_host: 192.168.56.31
        ansible_ssh_private_key_file: .vagrant/machines/testClient2/virtualbox/private_key
        vlan_id: 2
        vlan_ip: 10.10.10.254

