---
- name: VPN stand
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
  - debug:
      msg: "========== Start in {{ vpn_mode }} mode =========="

  roles:
  - openvpn

  post_tasks:
 
  - name: Run iperf3 on OpenVPN server
    ansible.builtin.shell: iperf3 -s -D -1
    when: 
      - ansible_hostname == "server"

  - name: Set up OpenVPN client and test
    block:

    - name: Copy private key for server
      ansible.builtin.copy:
        src: ../.vagrant/machines/server/virtualbox/private_key
        dest: /home/vagrant/server_key
        owner: vagrant
        group: vagrant
        mode: '0600'

    - name: Transfer key from OpenVPN server
      ansible.builtin.synchronize:
        mode: pull
        src: vagrant@192.168.60.10:/etc/openvpn/static.key
        dest: /etc/openvpn/static.key
        # set_remote_user: no
        private_key: /home/vagrant/server_key
        rsync_opts:
          - "-I --checksum --rsync-path='sudo -u root rsync'"
      delegate_to: client.loc
      become: true

    - name: Restart OpenVPN client
      ansible.builtin.systemd:
        state: restarted
        name: openvpn@server
        enabled: true

    - name: Run iperf3 on OpenVPN client
      ansible.builtin.shell: iperf3 -c 10.10.10.1 -t 40 -i 5
      register: command_output

    - name: Print iperf3 results
      ansible.builtin.debug:
        var: command_output.stdout_lines

    when: 
      - ansible_hostname == "client"
