{
 "title": "Timofey Biryukov",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Home Work Otus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Free disk space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"node-exporter:9100\", job=\"node\", mountpoint=\"/\",fstype!=\"tmpfs\"}/2048^3"
    }
   ]
  },
  {
   "title": "CPU utilazation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{instance=\"node-exporter:9100\", job=\"node\", mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"node-exporter:9100\", job=\"node\"} / (node_memory_MemTotal_bytes{instance=\"node-exporter:9100\", job=\"node\"} / 100)"
    }
   ]
  },
  {
   "title": "CPU LA 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg(node_load1{instance=\"node-exporter:9100\", job=\"node\"}) / count(count(node_cpu_seconds_total{instance=\"node-exporter:9100\", job=\"node\"}) by (cpu)) * 100"
    },
    {
     "expr": "avg(node_load5{instance=\"node-exporter:9100\", job=\"node\"}) / count(count(node_cpu_seconds_total{instance=\"node-exporter:9100\", job=\"node\"}) by (cpu)) * 100"
    },
    {
     "expr": "avg(node_load15{instance=\"node-exporter:9100\", job=\"node\"}) / count(count(node_cpu_seconds_total{instance=\"node-exporter:9100\", job=\"node\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "node_network_speed_bytes{device=\"eth0\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}