---
galaxy_info:
  role_name: rsyslog
  namespace: otus
  author: me
  description: Install and configure rsyslog server
  company: ""
  license: MIT
  min_ansible_version: 2.7
  platforms:
    - name: CentOS
      versions:
        - 7

  galaxy_tags: []
dependencies: []
