---
- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
  become: true

- name: reload nginx
  service:
    name: nginx
    state: reloaded
  become: true
