netplan_conf: |
  network:
    version: 2
    renderer: networkd
    ethernets:
      enp0s8:
        addresses:
        - 192.168.2.130/26
        routes:
        - to: 0.0.0.0/0
          via: 192.168.2.129
      enp0s16:
        addresses:
        - 192.168.60.21/24

ansible_private_key_file: .vagrant/machines/office1Server/virtualbox/private_key
