---

- name: Set time zone
  ansible.builtin.copy:
    remote_src: True
    src: /usr/share/zoneinfo/Europe/Moscow
    dest: /etc/localtime
    owner: root
    group: root
    mode: '0644'

- name: Restart service cron on centos
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: crond

- name: Put SELinux in permissive mode.
  ansible.posix.selinux:
    policy: targeted
    state: permissive
