error_logs: |
            error_log /var/log/nginx/error.log;
            error_log syslog:server=192.168.56.22:514,tag=nginx_error;

access_logs: "access_log syslog:server=192.168.56.22:514,tag=nginx_access,severity=info combined;"
