---
- name: NGINX | Install EPEL Repo package from standart repo
  ansible.builtin.yum:
    name: epel-release
    state: present
  become: true
  tags:
    - epel-package
    - packages

- name: NGINX | Install NGINX package from EPEL Repo
  ansible.builtin.yum:
    name: nginx
    state: latest
  become: true
  notify:
    - restart nginx
  tags:
    - nginx-package
    - packages

- name: NGINX | Create NGINX config file from template
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  become: true
  notify:
    - reload nginx
  tags:
    - nginx-configuration
